# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61bd0f13769732391bf77a028abbd9bbc5d6d5b9eb6a2f184b4e53d638b7f46228059c94b5f7b769f59212bb1f5b6537dd3f834b214598ba4264c32626b3903a

test:
  secret_key_base: 510f07080011ca799abbf711e173160a0b36afccc34a3650bec5525b2f3b110ca2483a54c83a65893e50e38c19b6c578cec7bcb7145e50bdc433218035ce6c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
